on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello, world!"
      - run: echo ${{ github.event.pull_request.number }}
      - run: echo ${{ github.event.pull_request.head.ref }}
      - run: echo ${{ github.event.pull_request.head.sha }}
      - run: echo "$GITHUB_SHA"
      - run: echo "$GITHUB_REF"
      - run: git rev-parse HEAD^@
